name: LLM Code Review

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  llm-code-review:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 拉代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ LLM Code Review（发表评论）
      - name: Run LLM Code Review
        id: llm-code-review
        uses: fit2cloud/LLM-CodeReview-Action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.ALIYUN_LLM_API_KEY }}
          OPENAI_API_ENDPOINT: https://dashscope.aliyuncs.com/compatible-mode/v1
          MODEL: qwen3-coder-plus
          LANGUAGE: Chinese
          PROMPT: |
            你是资深代码审查专家，请严格检查以下代码差异。

            ⚠️【必须遵守】
            - 判断只有当代码质量有问题时才加评论，否则请直接回复“/lgtm”。
            - 不要解释
            - 不要多余文本

          temperature: 0.2
          top_p: 1
          MAX_PATCH_LENGTH: 50000
          IGNORE_PATTERNS: "/node_modules,*.md,/dist,/.github"
          FILE_PATTERNS: "*.java,*.go,*.py,*.vue,*.ts,*.js,*.css,*.scss,*.html"